### ISSUE TITLE
redirect path를 따로 설정할 수 없을까요?

### ISSUE THREAD

**Issue by KimDoKy** [mango-tree/vue-kakao-login#1]
authorization code grant flow로 구현하고 있는데
backend 의 도메인이 frontend의 도메인과 달라서
redirect_uri 가 달라서 계속 에러가 발생합니다.

redirect_uri 만 따로 지정할 수 없을까요?

**Comment by mango-tree** [comment]
Redirect path 설정은 카카오 내부 설정이기 때문에 직접적으로 수정하는 것은 어려울 것 같습니다.
다만, onSuccess() 함수에서 Backend 서버로 token 값을 보내면 redirect_uri가 달라도 인증할 수 있을 것 같습니다.
