### ISSUE TITLE
안녕하세요?? 카카오 로그인 관련 문의 드립니다.

### ISSUE THREAD

**Issue by phpbae** [mango-tree/vue-kakao-login#2]
vue 컴포넌트로 만들어주셔서 감사하다는 말씀 먼저 올립니다.

문의사항은 로그인을 성공하여, 성공 콜백함수로 빠진경우,

해당 토큰값을 가지고

```
async onSuccess(data){
        console.log(data);

        // KaKao.API.request('/v2/user/me')
        const header = {
          Authorization : `${data.token_type} ${data.access_token}`
        };
        const userInfo = await this.$axios.get('https://kapi.kakao.com/v2/user/me', {
          header
        });

        console.log(userInfo);

      },
```

위와 같이 회원정보를 가지고 올려고 하는데, CORS 에러가 발생을 하더군요.
기존 JS에서는 KaKao.API.request('/v2/user/me') 이런식으로 사용을 하는데..
vue에도 설명이 빠진건지 아니면 지원이 안되는건지 궁금합니다.

**Comment by mango-tree** [comment]
안녕하세요, CORS문제는 라이브러리 문제가 아닌 카카오톡 API 문제로 보여집니다
현재 도메인이 카카오톡 API 허용 도메인에 들어가 있는지 확인해주세요
