### ISSUE TITLE
redirect issue

### ISSUE THREAD

**Issue by dalsoft-ktkim** [mango-tree/vue-kakao-login#3]
error="invalid_grant", error_description="Invalid redirect: JS-SDK does not match one of the registered values. Please check app settings on kakao developer site."

local에서 test 할때는 작동하는것을 확인했는데 ip 주소로 변경후 에러메세지가 계속 나오고 있습니다. 
redirect: JS-SDK이 경로를 바꿔 줄수 있는 방법이 있는지 문의 드립니다.

**Comment by mango-tree** [comment]
도메인 미스매치 오류인 것 같습니다
https://devtalk.kakao.com/t/javascript-unauthorized/53812/7
참고해 주세요
